spring:
  application:
    name: Spring-In-Action
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: sa
    password:
    url: "jdbc:h2:mem:tacocloud;DB_CLOSE_ON_EXIT=FALSE"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8081